services:
  database:
    build:
      context: ./source
      dockerfile: database/Dockerfile
    image: beta/database:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/countries.csv:/countries.csv
      - ./config/operators.csv:/operators.csv
      - ./config/prefixes.csv:/prefixes.csv
    networks:
      - beta_network

volumes:
  postgres_data:

networks:
  beta_network:
