services:
  database:
    build:
      context: ./source
      dockerfile: database/Dockerfile
    image: beta/database:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/countries.csv:/countries.csv
      - ./config/operators.csv:/operators.csv
      - ./config/prefixes.csv:/prefixes.csv
      - ./config/sor_plan.csv:/sor_plan.csv      
    networks:
      - beta_network


  data-generator:
    build:
      context: ./source
      dockerfile: tools/Dockerfile
    image: beta/data-generator:latest
    container_name: data-generator
    volumes:
      - ./WORK:/app/WORK
      - ./config/roam_out_ref.txt:/app/roam_out_ref.txt
      - ./config/roam_in_ref.txt:/app/roam_in_ref.txt
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1

  loader-service:
    build:
      context: ./source
      dockerfile: loader-service/Dockerfile
    image: beta/loader-service:latest
    container_name: loader-service
    volumes:
      - ./WORK:/app/WORK
      - ./.env:/app/.env 
      - ./config/config.yaml:/app/config.yaml 
    working_dir: /app
    environment:
      - RUST_LOG=info
    networks:
      - beta_network  

  analytics-service:
    build:
      context: ./source
      dockerfile: analytics-service/Dockerfile
    image: beta/analytics-service:latest
    container_name: analytics-service
    volumes:
      - ./.env:/app/.env 
    working_dir: /app
    environment:
      - RUST_LOG=info
    networks:
      - beta_network       

volumes:
  postgres_data:

networks:
  beta_network:
