services:
  database:
    image: postgres:17
    container_name: beta_roam_db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - beta_postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - beta_network

volumes:
  beta_postgres_data:

networks:
  beta_network:
