[package]
name = "loader-service"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
deadpool-postgres = "0.14.1"
tokio = { version = "1.44.2", features = ["full"] }
tokio-postgres = "0.7.13"
