[package]
name = "test_v02"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
datafusion = "45.0.0"
rand = "0.9.0"
rusqlite = "0.33.0"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
