sleep_duration_seconds: 60

sources:
  - source_type: roam_out
    source_directory: /home/dali/WORK/DATA/INPUT
    file_pattern: ^HSS\d{4}_\d{4}_\d{14}\.txt$
    post_action: archive
    archive_directory: /home/dali/WORK/DATA/ARCHIVE

  - source_type: roam_in
    source_directory: /tmpxx
    file_pattern: ^HSS\d{4}_\d{4}_\d{14}\.txt$
    post_action: delete

