[package]
name = "loader-service"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
