sources:
  - source_type: xxx
    source_directory: /home/dali/xxxx
    file_pattern: ^HSS\d{4}_\d{4}_\d{14}\.txt$
    post_action: archive
    archive_directory: /home/dali/yyyy

  - source_type: ROAM_OUT
    source_directory: WORK/INPUT/ROUT/
    file_pattern: ^HSS\d{4}_\d{4}_\d{14}\.txt$

  - source_type: ROAM_IN
    source_directory: WORK/INPUT/RIN/
    file_pattern: ^ROAM.*


