services:
  db:
    build: ./db-service
    env_file: .env  
    container_name: roam-db
    image: roam-db:v1.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-service/cr_database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: