[package]
name = "test_v05"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"