INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Afghanistan', 'AF', 'AFG', 4, '93');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Albania', 'AL', 'ALB', 8, '355');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Algeria', 'DZ', 'DZA', 12, '213');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('American Samoa', 'AS', 'ASM', 16, '1-684');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Andorra', 'AD', 'AND', 20, '376');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Angola', 'AO', 'AGO', 24, '244');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Anguilla', 'AI', 'AIA', 660, '1-264');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Antarctica', 'AQ', 'ATA', 10, '672');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Antigua and Barbuda', 'AG', 'ATG', 28, '1-268');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Argentina', 'AR', 'ARG', 32, '54');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Armenia', 'AM', 'ARM', 51, '374');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Aruba', 'AW', 'ABW', 533, '297');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Australia', 'AU', 'AUS', 36, '61');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Austria', 'AT', 'AUT', 40, '43');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Azerbaijan', 'AZ', 'AZE', 31, '994');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bahamas', 'BS', 'BHS', 44, '1-242');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bahrain', 'BH', 'BHR', 48, '973');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bangladesh', 'BD', 'BGD', 50, '880');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Barbados', 'BB', 'BRB', 52, '1-246');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Belarus', 'BY', 'BLR', 112, '375');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Belgium', 'BE', 'BEL', 56, '32');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Belize', 'BZ', 'BLZ', 84, '501');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Benin', 'BJ', 'BEN', 204, '229');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bermuda', 'BM', 'BMU', 60, '1-441');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bhutan', 'BT', 'BTN', 64, '975');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bolivia', 'BO', 'BOL', 68, '591');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bonaire', 'BQ', 'BES', 535, '599');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH', 70, '387');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Botswana', 'BW', 'BWA', 72, '267');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bouvet Island', 'BV', 'BVT', 74, '47');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Brazil', 'BR', 'BRA', 76, '55');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('British Indian Ocean Territory', 'IO', 'IOT', 86, '246');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Brunei Darussalam', 'BN', 'BRN', 96, '673');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Bulgaria', 'BG', 'BGR', 100, '359');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Burkina Faso', 'BF', 'BFA', 854, '226');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Burundi', 'BI', 'BDI', 108, '257');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cambodia', 'KH', 'KHM', 116, '855');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cameroon', 'CM', 'CMR', 120, '237');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Canada', 'CA', 'CAN', 124, '1');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cape Verde', 'CV', 'CPV', 132, '238');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cayman Islands', 'KY', 'CYM', 136, '1-345');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Central African Republic', 'CF', 'CAF', 140, '236');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Chad', 'TD', 'TCD', 148, '235');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Chile', 'CL', 'CHL', 152, '56');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('China', 'CN', 'CHN', 156, '86');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Christmas Island', 'CX', 'CXR', 162, '61');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cocos (Keeling) Islands', 'CC', 'CCK', 166, '61');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Colombia', 'CO', 'COL', 170, '57');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Comoros', 'KM', 'COM', 174, '269');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Congo', 'CG', 'COG', 178, '242');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Democratic Republic of the Congo', 'CD', 'COD', 180, '243');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cook Islands', 'CK', 'COK', 184, '682');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Costa Rica', 'CR', 'CRI', 188, '506');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Croatia', 'HR', 'HRV', 191, '385');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cuba', 'CU', 'CUB', 192, '53');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Curacao', 'CW', 'CUW', 531, '599');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cyprus', 'CY', 'CYP', 196, '357');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Czech Republic', 'CZ', 'CZE', 203, '420');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Cote d''Ivoire', 'CI', 'CIV', 384, '225');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Denmark', 'DK', 'DNK', 208, '45');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Djibouti', 'DJ', 'DJI', 262, '253');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Dominica', 'DM', 'DMA', 212, '1-767');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Dominican Republic', 'DO', 'DOM', 214, '1-809');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Dominican Republic', 'DO', 'DOM', 214, '1-829');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Dominican Republic', 'DO', 'DOM', 214, '1-849');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Ecuador', 'EC', 'ECU', 218, '593');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Egypt', 'EG', 'EGY', 818, '20');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('El Salvador', 'SV', 'SLV', 222, '503');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Equatorial Guinea', 'GQ', 'GNQ', 226, '240');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Eritrea', 'ER', 'ERI', 232, '291');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Estonia', 'EE', 'EST', 233, '372');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Ethiopia', 'ET', 'ETH', 231, '251');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Falkland Islands (Malvinas)', 'FK', 'FLK', 238, '500');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Faroe Islands', 'FO', 'FRO', 234, '298');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Fiji', 'FJ', 'FJI', 242, '679');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Finland', 'FI', 'FIN', 246, '358');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('France', 'FR', 'FRA', 250, '33');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('French Guiana', 'GF', 'GUF', 254, '594');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('French Polynesia', 'PF', 'PYF', 258, '689');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('French Southern Territories', 'TF', 'ATF', 260, '262');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Gabon', 'GA', 'GAB', 266, '241');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Gambia', 'GM', 'GMB', 270, '220');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Georgia', 'GE', 'GEO', 268, '995');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Germany', 'DE', 'DEU', 276, '49');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Ghana', 'GH', 'GHA', 288, '233');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Gibraltar', 'GI', 'GIB', 292, '350');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Greece', 'GR', 'GRC', 300, '30');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Greenland', 'GL', 'GRL', 304, '299');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Grenada', 'GD', 'GRD', 308, '1-473');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Guadeloupe', 'GP', 'GLP', 312, '590');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Guam', 'GU', 'GUM', 316, '1-671');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Guatemala', 'GT', 'GTM', 320, '502');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Guernsey', 'GG', 'GGY', 831, '44');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Guinea', 'GN', 'GIN', 324, '224');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Guinea-Bissau', 'GW', 'GNB', 624, '245');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Guyana', 'GY', 'GUY', 328, '592');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Haiti', 'HT', 'HTI', 332, '509');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Heard Island and McDonald Islands', 'HM', 'HMD', 334, '672');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Holy See (Vatican City State)', 'VA', 'VAT', 336, '379');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Honduras', 'HN', 'HND', 340, '504');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Hong Kong', 'HK', 'HKG', 344, '852');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Hungary', 'HU', 'HUN', 348, '36');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Iceland', 'IS', 'ISL', 352, '354');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('India', 'IN', 'IND', 356, '91');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Indonesia', 'ID', 'IDN', 360, '62');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Iran, Islamic Republic of', 'IR', 'IRN', 364, '98');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Iraq', 'IQ', 'IRQ', 368, '964');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Ireland', 'IE', 'IRL', 372, '353');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Isle of Man', 'IM', 'IMN', 833, '44');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Israel', 'IL', 'ISR', 376, '972');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Italy', 'IT', 'ITA', 380, '39');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Jamaica', 'JM', 'JAM', 388, '1-876');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Japan', 'JP', 'JPN', 392, '81');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Jersey', 'JE', 'JEY', 832, '44');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Jordan', 'JO', 'JOR', 400, '962');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Kazakhstan', 'KZ', 'KAZ', 398, '7');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Kenya', 'KE', 'KEN', 404, '254');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Kiribati', 'KI', 'KIR', 296, '686');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Korea, Democratic People''s Republic of', 'KP', 'PRK', 408, '850');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Korea, Republic of', 'KR', 'KOR', 410, '82');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Kuwait', 'KW', 'KWT', 414, '965');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Kyrgyzstan', 'KG', 'KGZ', 417, '996');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Lao People''s Democratic Republic', 'LA', 'LAO', 418, '856');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Latvia', 'LV', 'LVA', 428, '371');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Lebanon', 'LB', 'LBN', 422, '961');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Lesotho', 'LS', 'LSO', 426, '266');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Liberia', 'LR', 'LBR', 430, '231');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Libya', 'LY', 'LBY', 434, '218');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Liechtenstein', 'LI', 'LIE', 438, '423');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Lithuania', 'LT', 'LTU', 440, '370');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Luxembourg', 'LU', 'LUX', 442, '352');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Macao', 'MO', 'MAC', 446, '853');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Macedonia, the Former Yugoslav Republic of', 'MK', 'MKD', 807, '389');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Madagascar', 'MG', 'MDG', 450, '261');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Malawi', 'MW', 'MWI', 454, '265');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Malaysia', 'MY', 'MYS', 458, '60');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Maldives', 'MV', 'MDV', 462, '960');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Mali', 'ML', 'MLI', 466, '223');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Malta', 'MT', 'MLT', 470, '356');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Marshall Islands', 'MH', 'MHL', 584, '692');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Martinique', 'MQ', 'MTQ', 474, '596');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Mauritania', 'MR', 'MRT', 478, '222');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Mauritius', 'MU', 'MUS', 480, '230');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Mayotte', 'YT', 'MYT', 175, '262');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Mexico', 'MX', 'MEX', 484, '52');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Micronesia, Federated States of', 'FM', 'FSM', 583, '691');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Moldova, Republic of', 'MD', 'MDA', 498, '373');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Monaco', 'MC', 'MCO', 492, '377');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Mongolia', 'MN', 'MNG', 496, '976');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Montenegro', 'ME', 'MNE', 499, '382');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Montserrat', 'MS', 'MSR', 500, '1-664');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Morocco', 'MA', 'MAR', 504, '212');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Mozambique', 'MZ', 'MOZ', 508, '258');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Myanmar', 'MM', 'MMR', 104, '95');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Namibia', '\"NA\"', 'NAM', 516, '264');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Nauru', 'NR', 'NRU', 520, '674');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Nepal', 'NP', 'NPL', 524, '977');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Netherlands', 'NL', 'NLD', 528, '31');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('New Caledonia', 'NC', 'NCL', 540, '687');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('New Zealand', 'NZ', 'NZL', 554, '64');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Nicaragua', 'NI', 'NIC', 558, '505');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Niger', 'NE', 'NER', 562, '227');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Nigeria', 'NG', 'NGA', 566, '234');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Niue', 'NU', 'NIU', 570, '683');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Norfolk Island', 'NF', 'NFK', 574, '672');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Northern Mariana Islands', 'MP', 'MNP', 580, '1-670');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Norway', 'NO', 'NOR', 578, '47');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Oman', 'OM', 'OMN', 512, '968');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Pakistan', 'PK', 'PAK', 586, '92');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Palau', 'PW', 'PLW', 585, '680');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Palestine, State of', 'PS', 'PSE', 275, '970');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Panama', 'PA', 'PAN', 591, '507');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Papua New Guinea', 'PG', 'PNG', 598, '675');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Paraguay', 'PY', 'PRY', 600, '595');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Peru', 'PE', 'PER', 604, '51');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Philippines', 'PH', 'PHL', 608, '63');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Pitcairn', 'PN', 'PCN', 612, '870');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Poland', 'PL', 'POL', 616, '48');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Portugal', 'PT', 'PRT', 620, '351');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Puerto Rico', 'PR', 'PRI', 630, '1');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Qatar', 'QA', 'QAT', 634, '974');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Romania', 'RO', 'ROU', 642, '40');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Russian Federation', 'RU', 'RUS', 643, '7');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Rwanda', 'RW', 'RWA', 646, '250');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Reunion', 'RE', 'REU', 638, '262');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Saint Barthelemy', 'BL', 'BLM', 652, '590');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Saint Helena', 'SH', 'SHN', 654, '290');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Saint Kitts and Nevis', 'KN', 'KNA', 659, '1-869');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Saint Lucia', 'LC', 'LCA', 662, '1-758');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Saint Martin (French part)', 'MF', 'MAF', 663, '590');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Saint Pierre and Miquelon', 'PM', 'SPM', 666, '508');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VCT', 670, '1-784');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Samoa', 'WS', 'WSM', 882, '685');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('San Marino', 'SM', 'SMR', 674, '378');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Sao Tome and Principe', 'ST', 'STP', 678, '239');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Saudi Arabia', 'SA', 'SAU', 682, '966');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Senegal', 'SN', 'SEN', 686, '221');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Serbia', 'RS', 'SRB', 688, '381');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Seychelles', 'SC', 'SYC', 690, '248');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Sierra Leone', 'SL', 'SLE', 694, '232');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Singapore', 'SG', 'SGP', 702, '65');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Sint Maarten (Dutch part)', 'SX', 'SXM', 534, '1-721');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Slovakia', 'SK', 'SVK', 703, '421');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Slovenia', 'SI', 'SVN', 705, '386');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Solomon Islands', 'SB', 'SLB', 90, '677');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Somalia', 'SO', 'SOM', 706, '252');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('South Africa', 'ZA', 'ZAF', 710, '27');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239, '500');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('South Sudan', 'SS', 'SSD', 728, '211');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Spain', 'ES', 'ESP', 724, '34');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Sri Lanka', 'LK', 'LKA', 144, '94');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Sudan', 'SD', 'SDN', 729, '249');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Suriname', 'SR', 'SUR', 740, '597');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Svalbard and Jan Mayen', 'SJ', 'SJM', 744, '47');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Swaziland', 'SZ', 'SWZ', 748, '268');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Sweden', 'SE', 'SWE', 752, '46');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Switzerland', 'CH', 'CHE', 756, '41');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Syrian Arab Republic', 'SY', 'SYR', 760, '963');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Taiwan', 'TW', 'TWN', 158, '886');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Tajikistan', 'TJ', 'TJK', 762, '992');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('United Republic of Tanzania', 'TZ', 'TZA', 834, '255');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Thailand', 'TH', 'THA', 764, '66');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Timor-Leste', 'TL', 'TLS', 626, '670');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Togo', 'TG', 'TGO', 768, '228');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Tokelau', 'TK', 'TKL', 772, '690');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Tonga', 'TO', 'TON', 776, '676');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Trinidad and Tobago', 'TT', 'TTO', 780, '1-868');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Tunisia', 'TN', 'TUN', 788, '216');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Turkey', 'TR', 'TUR', 792, '90');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Turkmenistan', 'TM', 'TKM', 795, '993');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Turks and Caicos Islands', 'TC', 'TCA', 796, '1-649');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Tuvalu', 'TV', 'TUV', 798, '688');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Uganda', 'UG', 'UGA', 800, '256');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Ukraine', 'UA', 'UKR', 804, '380');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('United Arab Emirates', 'AE', 'ARE', 784, '971');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('United Kingdom', 'GB', 'GBR', 826, '44');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('United States', 'US', 'USA', 840, '1');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('United States Minor Outlying Islands', 'UM', 'UMI', 581, '1');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Uruguay', 'UY', 'URY', 858, '598');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Uzbekistan', 'UZ', 'UZB', 860, '998');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Vanuatu', 'VU', 'VUT', 548, '678');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Venezuela', 'VE', 'VEN', 862, '58');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Viet Nam', 'VN', 'VNM', 704, '84');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('British Virgin Islands', 'VG', 'VGB', 92, '1-284');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('US Virgin Islands', 'VI', 'VIR', 850, '1-340');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Wallis and Futuna', 'WF', 'WLF', 876, '681');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Western Sahara', 'EH', 'ESH', 732, '212');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Yemen', 'YE', 'YEM', 887, '967');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Zambia', 'ZM', 'ZMB', 894, '260');
INSERT INTO dim_countries (country, alpha2, alpha3, country_num, country_code) VALUES ('Zimbabwe', 'ZW', 'ZWE', 716, '263');